### ISSUE TITLE
Cannot update club logo

### ISSUE THREAD

**Issue by julaudo** [alexeil/sikb-api#11] opened 2019-04-16 09:21 UTC
**Application version**
version : 1.0.0-RC5

**Describe the bug**
When updating a club, the new logo URL is not persisted

**To Reproduce**
curl 'https://cors-anywhere.herokuapp.com/http://ec2-35-180-42-251.eu-west-3.compute.amazonaws.com:8080/sikb/api/v1/clubs/12' -X PUT -H 'Accept: application/json, text/plain, */*' -H 'Referer: http://localhost:8080/' -H 'Origin: null' -H 'access_token: MWUwZTc2ZGUtMWNiNy00YTQ5LWFmMTUtNDAwOWFjODJjY2I1MjAxOS0wNC0xNlQwOToxMjoyMy4zNjZa' -H 'Authorization: Basic YWRtaW46YWRtaW4=' -H 'Content-Type: application/json' --data-binary '{"id":12,"name":"Kin-Ball Association Rennes22","shortName":"KBAR22","logo":{"location":"http://kbar.kin-ball.fr/wp-content/uploads/2018/08/cropped-IMG_2418-2.jpg"}}' --compressed

The result show that the URL has not been updated;

{"id":12,"name":"Kin-Ball Association Rennes22","shortName":"KBAR22","logo":{"location":"http://ec2-35-180-42-251.eu-west-3.compute.amazonaws.com:8080/sikb/document/?type=logo&id=KBAR.png"}}

**Expected behavior**
URL should be updated

**Screenshots**
N/A

**Comment by alexeil** [comment] 2019-05-02 20:49
By design you need to call "POST /clubs/{clubId}/logo" instead of "PUT /clubs/{clubId}". 
There is a technical limitation in OpenApi Code gen which might be fix in further release. Until i will close this issue.

**Closed by alexeil** 2019-05-02 20:49 UTC
Labels: wontfix
